name: flutter_skeleton
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Responsive screen UI
  sizer: ^2.0.15

  #Getx & Dependency Management
  get: ^4.6.5
  get_it: ^7.6.0

  #SVG images
  flutter_svg: ^2.0.5

  #Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  #Directory
  path_provider: ^2.0.15

  #BASE
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_native_splash: ^2.2.19
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.1

  #Flutter generator
  flutter_gen: ^5.3.1

  #URL/Intent Launcher
  url_launcher: ^6.1.11

  #Permission Handler
  permission_handler: ^10.3.0

  #Networking
  dio: ^5.2.1+1

  #Cahced Network Image
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/values/colors.xml

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/values/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: DMSansBold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
    - family: DMSansMedium
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf